SELECT CAR.CAR_ID, CAR.CAR_TYPE, CAST(CAR.DAILY_FEE * 30 * ((100 - A.DISCOUNT_RATE) / 100) AS UNSIGNED) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR CAR 
    INNER JOIN 
        (SELECT 
            CAR_TYPE, DISCOUNT_RATE 
        FROM 
            CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
        WHERE CAR_TYPE IN ('SUV', '세단') AND DURATION_TYPE = '30일 이상') A
    ON CAR.CAR_TYPE = A.CAR_TYPE
WHERE 
    CAR.CAR_TYPE IN ('SUV', '세단')
    AND CAR.CAR_ID NOT IN 
        (SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE END_DATE >= '2022-11-01')
    AND
    CAR.DAILY_FEE * 30 * ((100 - A.DISCOUNT_RATE) / 100) >= 500000 
    AND 
    CAR.DAILY_FEE * 30 * ((100 - A.DISCOUNT_RATE) / 100) < 2000000
ORDER BY FEE DESC, CAR.CAR_TYPE ASC, CAR.CAR_ID DESC;
    
    





