SELECT 
    YEAR(S.SALES_DATE) AS 'YEAR', 
    MONTH(S.SALES_DATE) AS 'MONTH', 
    U.GENDER, 
    COUNT(DISTINCT U.USER_ID) AS 'USERS'
FROM USER_INFO U, ONLINE_SALE S
WHERE 
    U.USER_ID = S.USER_ID AND
    U.GENDER IS NOT NULL
GROUP BY 
    DATE_FORMAT(S.SALES_DATE, '%Y-%m'), U.GENDER
HAVING
    COUNT(*)>0
ORDER BY YEAR, MONTH, GENDER