WITH RENTED_CARS AS (
    -- 2022년 10월 16일에 대여 중인 자동차 목록
    SELECT DISTINCT CAR_ID, '대여중' AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
)

SELECT 
    C.CAR_ID,
    COALESCE(R.AVAILABILITY, '대여 가능') AS AVAILABILITY
FROM 
    (SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) C
    LEFT JOIN RENTED_CARS R ON C.CAR_ID = R.CAR_ID
ORDER BY C.CAR_ID DESC;
