# SELECT
#     MONTH(START_DATE) AS MONTH
#     , CAR_ID
#     , COUNT(HISTORY_ID) AS RECORDS
# FROM 
#     CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# WHERE
#     START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
# GROUP BY
#     CAR_ID
# HAVING
#     COUNT(HISTORY_ID) >= 5
# ORDER BY
#     MONTH(START_DATE) ASC, CAR_ID DESC;

# WITH HIST AS (SELECT *
# FROM 
#     CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# WHERE
#     START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
# GROUP BY
#     CAR_ID
# HAVING
#     COUNT(HISTORY_ID) >= 5)

WITH HIST AS (
    SELECT 
        CAR_ID
        , COUNT(*) AS TOTAL_COUNT
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE
        START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
    GROUP BY
        CAR_ID
    HAVING
        COUNT(HISTORY_ID) >= 5)
    
SELECT 
    MONTH(START_DATE) AS MONTH
    , H.CAR_ID AS CAR_ID
    , COUNT(*) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN 
    HIST 
    ON H.CAR_ID = HIST.CAR_ID
WHERE 
    START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
GROUP BY MONTH(H.START_DATE), H.CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;