WITH FIX AS (
    SELECT FISH_TYPE, IFNULL(LENGTH, 10) AS LENGTH
    FROM FISH_INFO
)

-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FIX
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE;